### ISSUE TITLE
Unable to install Node.js

### ISSUE THREAD

**Issue by sholladay** [mfichman/winbrew#15]
Hi! I love that this project exists. Thanks for your hard work. :)

I am having trouble installing Node. Although the error doesn't seem specific to the formula, I cannot rule that out.

It is happening on a fresh copy of Windows 10, with Python 2.7.12, Git 2.9.3, and Visual Studio 2015 (14.0.25425.01 Update 3). Below is the trace from PowerShell, similar things occur in cmd.exe, etc. I am not using Cygwin, a virtual machine, or anything else out of the norm. Could be that I am missing a prerequisite, but if so I am not sure what.

```
PS C:\Windows\system32> winbrew install nodejs
downloading nodejs
unpacking nodejs
installing nodejs
Traceback (most recent call last):
  File "C:\Python27\Scripts\winbrew-script.py", line 9, in <module>
    load_entry_point('winbrew==1.1.7', 'console_scripts', 'winbrew')()
  File "c:\python27\lib\site-packages\winbrew\execute.py", line 268, in main
    install(args)
  File "c:\python27\lib\site-packages\winbrew\execute.py", line 153, in install
    InstallPlan(formulas, args).execute()
  File "c:\python27\lib\site-packages\winbrew\execute.py", line 71, in execute
    formula.setup()
  File "c:\python27\lib\site-packages\winbrew\formula.py", line 176, in setup
    'INCLUDE': ';'.join((os.environ['INCLUDE'], winbrew.include_path)),
  File "c:\python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'INCLUDE'
```

**Comment by mfichman** [comment]
@sholladay Can you try running `winbrew` in the Visual Studio Command Prompt? (The fact that you need to do that may be a hole in the documentation -- I'll look into it.)

If that doesn't work, reply here and I'll see what I can do!

**Comment by mfichman** [comment]
Also, thanks for your interest in the project!

**Comment by sholladay** [comment]
Hi @mfichman apologies for the delayed response. This still isn't working for me.

Here is a gist with the output from the Developer Command Prompt: https://gist.github.com/sholladay/a361cc3a10e29aed72d92f455375cdfe

I did perhaps break the rules by installing VS 2017 instead of 2015. Could that be a problem? The output seems to indicate that the script found VS 2015 somehow, so I assume it has what it needs, but maybe not.

Also, I am on 64-bit Windows 10, but it seems to be trying to install a 32-bit version of Node. Not sure if that could play into this at all.

**Comment by mfichman** [comment]
@sholladay I recently updated Winbrew to use VS 2017, so that's OK. On the other hand, the fact that Winbrew is installing the 32-bit version of Node is definitely a bug. 

Some background: Winbrew should always install 64-bit software; I made the decision to support only the latest VS version and 64-bit only a while back (limited resources!)

I'll take a look at it myself, and get back to you! Thanks for reporting the issue.

**Comment by mfichman** [comment]
@sholladay I think I've resolved the issue in v1.1.9. Please run:
```
pip install --upgrade winbrew
```
If it still doesn't work, first make sure you're using the x86 x64 Cross Tools Command Prompt for VS 2017. That environment is usually found here:

```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsx86_amd64.bat"
```

You can also find the shortcut in the Start Menu.

If that still doesn't work, sent me the output of the `set` command, run the environment you ran `winbrew` from. Thanks!
